[package]
name = "junit-report"
version = "0.6.0"
authors = ["Pascal Bach <pascal.bach@nextrem.ch>"]
description = "Create JUnit compatible XML reports."
license = "MIT"
repository = "https://github.com/bachp/junit-report-rs"
keywords = ["junit", "xunit", "xml", "report"]
readme = "README.md"
edition = "2018"

[dependencies]
derive-getters = "0.2.0"
strip-ansi-escapes = "0.1.0"
thiserror = "1.0.19"
time = { version = "0.3.4", features = ["formatting", "macros"] }
xml-rs = "0.8.3"

[dev-dependencies]
commandspec = "0.12.2"
doc-comment = "0.3.3"
